# -*- coding: utf-8 -*-
"""arayuzu hazir.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WzZz4vROiAPTVCRKjQoLXWTcDMxxNIni
"""

!pkill -9 streamlit
!pkill -9 npx

# 1. Mevcut süreçleri temizleyelim ki çakışma olmasın
!pkill streamlit
!pkill npx

# 2. Gerekli kütüphaneyi kuralım
!pip install streamlit -q

import streamlit as st
import pandas as pd
import numpy as np

# EVEYES 360 Ayarları
st.set_page_config(page_title="EVEYES 360 Portal", layout="wide")

# Kenar Çubuğu - İşte o çalışmayan menü burası
st.sidebar.title("💠 EVEYES 360")
dil = st.sidebar.selectbox("Dil Seçiniz", ["Türkçe", "English", "Yoruba", "Français"])
sayfa = st.sidebar.radio("Sayfa Değiştir", ["📱 Ana Ekran", "📊 Bilimsel Analiz (Makale)"])

if sayfa == "📱 Ana Ekran":
    st.title(f"🚀 Hoş Geldiniz - {dil}")
    st.write("EVEYES 360 Abuja Merkezinden Canlı Yayın")

    mesaj = st.text_input("Sisteme bir not bırakın:")
    if st.button("Kaydet ve İmzala"):
        st.success(f"'{mesaj}' notu kaydedildi. (Ledger Nano X onayı bekleniyor...)")
        st.balloons()

elif sayfa == "📊 Bilimsel Analiz (Makale)":
    st.title("📄 Bilimsel Makale ve Frekans Verileri")
    st.markdown("### Selçuklu Tıbbı ve Biosonoloji")

    # Canlı Grafik Fonksiyonu
    chart_data = pd.DataFrame(np.random.randn(20, 2), columns=['Rast Makamı', 'Rehavi Makamı'])
    st.line_chart(chart_data)

    # Selçuklu ve Biosonoloji Tablosu
    data = {
        "Makam": ["Rast", "Rehavi", "Hicaz"],
        "Etki Alanı": ["Göz/Kemik", "Sinir Sistemi", "Kalp/Kan"],
        "Frekans (Hz)": ["432 Hz", "528 Hz", "396 Hz"]
    }
    st.table(pd.DataFrame(data))

"""# 3. app.py dosyasını BİLİMSEL TABLO VE HAREKETLİ GRAFİKLE yeniden yazalım
with open('app.py', 'w', encoding='utf-8') as f:
    f.write("""
import streamlit as st
import pandas as pd
import numpy as np
import time

st.set_page_config(page_title="EVEYES 360 - Canlı Portal", layout="wide")

# Kenar Çubuğu
st.sidebar.title("💠 EVEYES 360")
menu = st.sidebar.radio("Menü", ["Ana Ekran", "Bilimsel Makale & Frekans", "Ledger Güvenliği"])

if menu == "Ana Ekran":
    st.title("🚀 EVEYES 360 Canlı Sosyal Akış")
    st.write("Abuja 16 Ocak 2026 - Sistem Aktif")

    # Hareketli bir karşılama
    st.balloons()

    msg = st.text_input("Düşünceni Yaz:")
    if st.button("Sisteme Gönder"):
        with st.spinner('Veri şifreleniyor...'):
            time.sleep(1)
            st.success("Gönderi EVEYES 360 veritabanına işlendi!")

elif menu == "Bilimsel Makale & Frekans":
    st.title("📄 Selçuklu Tıbbı & Biosonoloji Verileri")

    # TABLO BURADA (Artık ekranda göreceksin)
    data = {
        "Selçuklu Makamı": ["Rast", "Rehavi", "Hicaz", "Uşşak"],
        "Etkilenmiş Hücre": ["Göz", "Nöronlar", "Ürogenital", "Kalp"],
        "Frekans (Hz)": ["432 Hz", "528 Hz", "396 Hz", "528 Hz"],
        "Modern Tıp Etkisi": ["Yatıştırıcı", "DNA Onarımı", "Stres Azaltıcı", "Yenilenme"]
    }
    st.table(pd.DataFrame(data))

    # HAREKET BURADA: Canlı Frekans Grafiği
    st.subheader("📊 Canlı Hücresel Rezonans Grafiği")
    chart_data = pd.DataFrame(np.random.randn(20, 3), columns=['Rast', 'Rehavi', 'Hicaz'])
    st.line_chart(chart_data)
    st.caption("Selçuklu makamlarının anlık biosonolojik frekans çıktıları simüle ediliyor.")

elif menu == "Ledger Güvenliği":
    st.title("🔒 Donanım Kilidi")
    st.info("Ledger Nano X cihazınızı USB üzerinden bağlamanız bekleniyor...")
    st.progress(0) # Hareketli bir bar
""")
"""

#!streamlit run app.py & npx localtunnel --port 8501

with open('app.py', 'w', encoding='utf-8') as f:
    f.write("""
import streamlit as st
import pandas as pd
import numpy as np

# EVEYES 360 Ayarları
st.set_page_config(page_title="EVEYES 360 Portal", layout="wide")

# Kenar Çubuğu - Fonksiyonel Menü
st.sidebar.title("💠 EVEYES 360")
# Dil seçeneği kuralını uyguluyoruz
dil = st.sidebar.selectbox("Dil Seçiniz", ["Türkçe", "English", "Yoruba", "Français"])
sayfa = st.sidebar.radio("Sayfa Değiştir", ["📱 Ana Ekran", "📊 Bilimsel Analiz (Makale)"])

if sayfa == "📱 Ana Ekran":
    st.title(f"🚀 Hoş Geldiniz - {dil}")
    st.write("EVEYES 360 Abuja Merkezinden Canlı Yayın")

    # Gerçek bir fonksiyon: Mesaj Kutusu
    mesaj = st.text_input("Sisteme bir not bırakın:")
    if st.button("Kaydet ve İmzala"):
        if mesaj:
            st.success(f"'{mesaj}' notu kaydedildi. (Ledger Nano X onayı bekleniyor...)")
            st.balloons() # Sayfada hareket!

elif sayfa == "📊 Bilimsel Analiz (Makale)":
    st.title("📄 Bilimsel Makale ve Frekans Verileri")
    st.markdown("### Selçuklu Tıbbı ve Biosonoloji")

    # Hareketli Grafik Fonksiyonu
    st.write("Canlı Hücre Rezonans Takibi:")
    chart_data = pd.DataFrame(np.random.randn(20, 2), columns=['Rast Makamı', 'Rehavi Makamı'])
    st.line_chart(chart_data) # Sayfada sürekli değişen grafik!

    # Bilimsel Tablo
    data = {
        "Makam": ["Rast", "Rehavi", "Hicaz"],
        "Etki Alanı": ["Göz/Kemik", "Sinir Sistemi", "Kalp/Kan"],
        "Frekans (Hz)": ["432 Hz", "528 Hz", "396 Hz"]
    }
    st.table(pd.DataFrame(data)) # Profesyonel tablo görünümü
""")

# 4. IP Adresini Göster ve Başlat
print("\n" + "="*50)
print("SİTE ŞİFRESİ (ENDPOINT IP):")
!curl ipv4.icanhazip.com
print("="*50 + "\n")

# Uygulamayı Başlat
!streamlit run app.py & npx localtunnel --port 8501